```{r}
BiocManager::install(c("VariantTools", "Rsamtools", "GenomicRanges", "GenomicFeatures", "VariantAnnotation", "BiocParallel", force=TRUE))
```

```{r}
library(VariantTools)
library(Rsamtools)
library(GenomicRanges)
library(GenomicFeatures)
library(VariantAnnotation)
library(BiocParallel)
```

## Zadanie 3: Konfiguracja środowiska pracy

```{r}
#Ustaw katalog roboczy:
setwd("C:/Users/s207321/Desktop/alignment)


#Sprawdź, czy pliki są dostępne:
list.files()
```

## Zadanie 4: Wczytanie danych

```{r}
#wczytanie pliku BAM
bamfile <- "C:/Users/s207321/Desktop/alignment/aligned_sample.BAM"
bam <- BamFile(bamfile)

#wczytanie genomu referencyjnego
ref_genome <- "C:/Users/s207321/Desktop/alignment/ecoli_reference.fasta"
fa <- FaFile(ref_genome)
```

# Sortowanie plików BAM według współrzędnych

```{r}
input_bam <- "C:/Users/s207321/Desktop/alignment/aligned_sample.BAM"
output_bam <- "C:/Users/s207321/Desktop/alignment/sorted_aligned_sample.BAM"

sortBam(file = input_bam, destination = output_bam, overwrite = TRUE)

sorted_bam <- "C:/Users/s207321/Desktop/alignment/sorted_aligned_sample.BAM.bam"
```

# Indeksowanie pliku FASTA i BAM

```{R}
indexFa(ref_genome)
indexBam(sorted_bam)
```

## Zadanie 5: Kontrola jakości danych sekwencyjnych

```{r}
scanBamHeader(bam)

idxstats <- idxstatsBam(sorted_bam)
print(idxstats)

coverage_data <- coverage(sorted_bam)
summary(coverage_data[[1]]) # dla genomów prokariota

plot(coverage_data[[1]], main="Pokrycie genomu dla sekwencji U00096.3", ylab="Pokrycie", xlab="Pozycja w genomie")
```

## Zadanie 6: Wykrywanie wariantów

```{r}
# Ustaw parametry pileup
pileup_param <- PileupParam(
    distinguish_strands = FALSE,
    distinguish_nucleotides = TRUE,
    min_base_quality = 20
)

# Wykonaj pileup
pile <- pileup(sorted_bam, scanBamParam = ScanBamParam(), pileupParam = pileup_param)

# Konwertuj dane pileup do ramki danych z uzgodnieniem nazw sekwencji
library(dplyr)

pile_df <- as.data.frame(pile)
class(pile_df)

pile_df <- pile_df %>%
    mutate(seqnames = as.character(seqnames)) %>%
    mutate(seqnames = ifelse(seqnames == "U00096.3", "NC_000913.3", seqnames))

# Pogrupuj dane według pozycji
variant_candidates <- pile_df %>%
    group_by(seqnames, pos) %>%
    summarise(
        total = sum(count),
        A = sum(count[nucleotide == "A"]),
        C = sum(count[nucleotide == "C"]),
        G = sum(count[nucleotide == "G"]),
        T = sum(count[nucleotide == "T"]),
        .groups = 'drop'
    ) %>%
    mutate(
        ref = as.character(getSeq(fa, GRanges(seqnames, IRanges(pos, pos))))
    ) %>%
    rowwise() %>%
    mutate(
        # Obliczanie alternatywnych alleli
        alt_alleles = list(setdiff(c("A", "C", "G", "T"), ref)),
        # Liczenie odczytów dla referencyjnego i alternatywnych alleli
        ref_count = sum(c_across(c("A", "C", "G", "T"))[ref]),
        alt_count = sum(c_across(c("A", "C", "G", "T"))[alt_alleles])
    ) %>%
    ungroup() %>%
    # Filtracja na podstawie minimalnej liczby odczytów dla wariantu
    filter(alt_count >= 5) %>%
    # Opcjonalne filtrowanie na podstawie proporcji
    filter((alt_count / total) >= 0.2)

# Przykład wyświetlenia wariantów
head(variant_candidates)
```

## Zadanie 7: Filtracja i eksportowanie wyników do pliku

```{r}
# Filtracja wariantów na podstawie jakości i głębokości pokrycia
filtered_variants <- variant_candidates %>%
    filter(total >= 10, alt_count / total >= 0.2, alt_count >= 5)

# Wyświetlenie liczby wariantów przed i po filtrowaniu
cat("Liczba wariantów przed filtrowaniem:", nrow(variant_candidates), "\n")
cat("Liczba wariantów po filtrowaniu:", nrow(filtered_variants), "\n")

# Konwersja do data.frame dla eksportu
df_variants <- as.data.frame(filtered_variants)

# Eksport do pliku CSV
write.csv(df_variants, "C:/Users/s207321/Desktop/alignment/wyniki_wariantow.csv", row.names = FALSE)
```
